configs:
  params:
    server.insecure: true      # TLS terminates at the ALB
server:
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.mindville.online
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: kuda-replica
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
      alb.ingress.kubernetes.io/healthcheck-path: /healthz