configs:
  params:
    server.insecure: true      # TLS terminates at the ALB
server:
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.mindville.online
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: kuda-replica
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificateArn: arn:aws:acm:us-east-1:377510222088:certificate/fe117273-602a-4631-b98c-2d35808e5bcc
